spring.application.name=CatalogoBrinquedos
spring.datasource.url=jdbc:mysql://localhost:3306/loja_brinquedos
spring.datasource.password=root
spring.datasource.username=root

# O Spring tenta ler a variavel ${DB_PASSWORD}. O que vem depois dos dois pontos (:) 
# e o valor que ele usara caso nao encontre a variavel no sistema.

# Isso aqui faz o Spring criar as tabelas automaticamente no banco de dados (MySQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
# Define o tamanho máximo de cada arquivo de imagem
spring.servlet.multipart.max-file-size=5MB
# Define o tamanho máximo total da requisição
spring.servlet.multipart.max-request-size=5MB